systemd/networkmanager: don't build docs
This doens't work with crossdirect since apparently it calls the
compiler during package() stage:

ERROR: Error in gtkdoc helper script:

ERROR: ['/usr/bin/gtkdoc-scangobj', .... failed with status 1
============================================================================================
ERROR: crossdirect was called with: LD_PRELOAD=libfakeroot.so